### ISSUE TITLE
Screenshots in Readme and maybe Production?

### ISSUE THREAD

**Issue by hasib-rashid** [Milo123459/vext#2]
Hello there. This thing looks really solid and a number of people can try this. I am really interested in this program.

I just had a suggestion that maybe if you would have like some screenshots of how it works and looks then this repo will be even more attractive and many people can then use it.

And Just maybe (its your choice) you can make this for production like `glitter` so that people can actually use this like vim.

❤️ Love your work

**Comment by Milo123459** [comment]
Hey, thanks for showing interest!
I'm currently on holiday, so haven't had time to work on it. Vext should be done soon tho, so stay tuned!
Also, thanks for the kind words. I appreciate them, and you have no idea what they mean to an open source maintainer.
I'll add screenshots when it's done, thanks for the suggestion!
